    name: Build and Test Kalah

    on:
      push:
        branches:
          - submission
    jobs:
      build:
        name: Run make with target tests
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - uses: actions/setup-java@v1.4.3
            with:
                 java-version: 1.7
          - run: make tests
